=== EFREI-M1-LSI-2020-2021/xml-json/TP_2/Exercice 1/contact.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="contact_type">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="phone" type="xs:int" />
            <xs:element name="address">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="street" type="xs:string" />
                        <xs:element name="number" type="xs:int" />
                        <xs:element name="city" type="xs:string" />
                        <xs:element name="country" type="xs:string" />
                        <xs:choice minOccurs="1" maxOccurs="1">
                            <xs:element name="zip" type="xs:int" />
                            <xs:element name="cedex" type="xs:int" />
                        </xs:choice>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="person">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="contact_type">
                    <xs:sequence>
                        <xs:element name="firstname" type="xs:string"/>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="company">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="contact_type" />
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="contacts">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="person"/>
                <xs:element ref="company"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== EFREI-M1-LSI-2020-2021/xml-json/TP_2/Exercice 1/contact.xml
<?xml version="1.0" encoding="UTF-8"?>
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="contact.xsd">
    <person>
        <name>Ulluoa</name>
        <phone>0680817694</phone>
        <address>
            <street>Test</street>
            <number>10</number>
            <city>Paris</city>
            <country>France</country>
            <zip>75000</zip>
        </address>
        <firstname>Toto</firstname>
    </person>
    <company>
        <name>EFREI</name>
        <phone>0680817694</phone>
        <address>
            <street>Test</street>
            <number>10</number>
            <city>Paris</city>
            <country>France</country>
            <cedex>75000</cedex>
        </address>
    </company>
</contacts>
