=== EFREI-M1-LSI-2020-2021/xml-json/TP_2/Exercice 3/math.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="apply">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="1">
                    <xs:element name="cn" type="xs:double" />
                    <xs:element ref="apply" />
                </xs:choice>
                <xs:choice minOccurs="1">
                    <xs:element name="plus" nillable="true" />
                    <xs:element name="times" nillable="true" />
                </xs:choice>
                <xs:choice minOccurs="1">
                    <xs:element name="cn" type="xs:double" />
                    <xs:element ref="apply" />
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== EFREI-M1-LSI-2020-2021/xml-json/TP_2/Exercice 3/math.xml
<?xml version="1.0" encoding="UTF-8"?>
<apply xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="math.xsd">
    <apply>
        <cn>2</cn>
        <plus />
        <apply>
            <cn>2</cn>
            <plus />
            <cn>3</cn>
        </apply>
    </apply>
    <times />
    <cn>4</cn>
</apply>
